language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/travis_ci_test
install:
  - pip install pipenv
  - pipenv install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test