language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/travis_ci_test
install:
  - pip install pipenv
  - pipenv install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py collectstatic
script:
  - python manage.py test
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL